apiVersion: v1
kind: Secret
metadata:
  name: {{ include "musicarr.fullname" . }}-secrets
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ .Values.secrets.connectionString | quote }}
  Jellyfin__ApiKey: {{ .Values.secrets.jellyfinApiKey | quote }}
  Lidarr__ApiKey: {{ .Values.secrets.lidarrApiKey | quote }}
