apiVersion: v1
kind: ConfigMap
metadata:
  name: musicarr-config
  namespace: musicarr
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5000"
  Jellyfin__BaseUrl: "http://jellyfin:8096"
  Lidarr__BaseUrl: "http://lidarr:8686"
  MusicDiscovery__Provider: "MusicBrainz"
