apiVersion: v1
kind: Secret
metadata:
  name: musicarr-secrets
  namespace: musicarr
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres;Database=musicarr;Username=musicarr;******"
  Jellyfin__ApiKey: "changeme"
  Lidarr__ApiKey: "changeme"
